title: "Rapid Prototypes"
description: "Treat ideas as cattle, not pets."
baseurl: "/blog"
url: "https://tim-fan.github.io"
markdown: kramdown


defaults:
  - scope:
      path: "_posts/chalk_line_follower"
      type: posts
    values:
      categories: [chalk_line_follower]
  - scope:
      path: "_posts/solar_lawn_cutter"
      type: posts
    values:
      categories: [solar_lawn_cutter]
