title: "Rapid Prototypes"
description: "Treat ideas like cattle, not pets."
baseurl: "/blog"
url: "https://tim-fan.github.io"
markdown: kramdown






defaults:
  - scope:
      path: "_posts/chalk_line_follower"
      type: posts
    values:
      categories: [chalk_line_follower]
  - scope:
      path: "_posts/dig_through"
      type: posts
    values:
      categories: [dig_through]
  - scope:
      path: "_posts/festivity_maps"
      type: posts
    values:
      categories: [festivity_maps]
  - scope:
      path: "_posts/lets_read"
      type: posts
    values:
      categories: [lets_read]
  - scope:
      path: "_posts/plane_search"
      type: posts
    values:
      categories: [plane_search]
  - scope:
      path: "_posts/solar_lawn_cutter"
      type: posts
    values:
      categories: [solar_lawn_cutter]
